name: Script Python(Model)

on: [push]

jobs:
  run_script_python:
    runs-on: ubuntu-latest
    steps:

      - name: Check conteudo do repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instala python 3.12.2
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Instalação das dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load environment variables from .env
        run: |
          cat .env | grep -v '^#' | grep -v '^$' | while IFS= read -r line
          do
          echo "$line" >> $GITHUB_ENV
          done

      - name: Run your application
        run: |
          echo "Database URL is $Database"

      - name: Execução script python (model.py)
        run: python SRC/model/model.py

      - name: Realiza commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "up model.pkl"

      - name: Execução script python (db_csv.py)
        run: python SRC/ETL/db_csv.py

      - name: Realiza commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "up data_var.csv"
