name: Script Python(Model)

on: [push]

jobs:
  run_script_python:
    runs-on: ubuntu-latest
    steps:

      - name: Check conteudo do repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instala python 3.12.2
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Instalação do poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configuração Poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install

      - name: Executa script python
        run: python -m poetry run SRC/model/model.py
