name: Script

on: [push]

jobs:
  run_dataClear:
    runs-on: ubuntu-latest
    steps:

      - name: Check conteudo do repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instala python 3.12.2
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Instala os pacotes/bibliotecas (Poetry)
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
